# Site settings
title: Dex's blog 
description: "Musings of a computer scientist."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.dex.moe" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dexhunter 
future: true
comment-support: utterances

# Build settings
markdown: kramdown
theme: minima 
disqus:
    shortname: dexhunter

utterances:
    repo: dexhunter/blog.dex.moe
    issue-term: pathname
    theme: github-light

google_analytics: UA-96340754-2
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-last-modified-at
exclude:
  - Gemfile
  - Gemfile.lock
